### PR TITLE
SES6 make check in Python 3-only env

### PR DESCRIPTION
**Pull request by smithfarm**
Unfortunately this has to be downstream-only for now - upstream cannot do this until CentOS/RHEL starts including Python 3 in their base distros.

Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1090072

### CODE REVIEW

**Comment by smithfarm** [comment]
Added a commit to fix https://bugzilla.suse.com/show_bug.cgi?id=1090072

**Comment by smithfarm** [comment]
Intriguingly, upstream master "make check" now passes on my py3-only Leap 15.0 box.

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
retest this please

**Pull request closed without merging**
