### PR TITLE
cephadm: update monitoring container images

### PR DESCRIPTION
**Pull request by s0nea**
- Node exporter: registry.suse.com/ses/7.1/ceph/prometheus-node-exporter:1.3.0
- Alertmanager: registry.suse.com/ses/7.1/ceph/prometheus-alertmanager:0.23.0
- Grafana: registry.suse.com/ses/7.1/ceph/grafana:8.3.10

Signed-off-by: Tatjana Dehler <tdehler@suse.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by mgfritch — APPROVED** [review]
lgtm! Feel free to merge when ready

**Comment by s0nea** [comment]
> lgtm! Feel free to merge when ready

Thank you for the approval!

Everything is read I think. Except the Grafana image on the registry is still outdated and need to be rebuilt. I'm not sure if I should convert this draft into a "normal" PR now anyway.

**Review by tserong — APPROVED** [review]

**Comment by tserong** [comment]
Oh, wait, I just realised the commit message needs to say "Grafana: registry.suse.com/ses/7.1/ceph/grafana:8.3.10", not 8.3.5. Anyway, the change itself looks fine to me :-)

**Comment by s0nea** [comment]
> Oh, wait, I just realised the commit message needs to say "Grafana: registry.suse.com/ses/7.1/ceph/grafana:8.3.10", not 8.3.5. Anyway, the change itself looks fine to me :-)

Oh, right. Thanks for pointing it out. The package has been upgraded after my commit. I'll update the commit message.

**Pull request merged**
