### PR TITLE
[SES5] orphan fixes full

### PR DESCRIPTION
**Pull request by theanalyst**
- [x] merge https://github.com/ceph/ceph/pull/28314
- [ ] luminous v12.2.13 released
- [ ] merge upstream luminous into downstream ses5
- [ ] include bsc#1111164 in ceph.changes
- [ ] MR
- [ ] close this PR

### CODE REVIEW

**Comment by theanalyst** [comment]
test this please

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
Could you please rebase

**Comment by smithfarm** [comment]
@theanalyst Do we still need this one?

**Comment by theanalyst** [comment]
Yes, the backport tracker is still not resolved, lets get this in http://tracker.ceph.com/issues/39117

**Comment by smithfarm** [comment]
@theanalyst OK, opened https://github.com/ceph/ceph/pull/28314

**Comment by smithfarm** [comment]
This already found its way into SES5 via https://github.com/ceph/ceph/pull/28314

**Pull request closed without merging**
