### PR TITLE
Remove last vestiges of docker.io image paths

### PR DESCRIPTION
**Pull request by tserong**
Two things here, the main issue being setting the default container_image to registry.suse.com/ses/7.1/ceph/ceph. The other thing is the `normalize_image_digest()` function, which AFAICT is extremely unlikely to actually cause trouble, but just in case it does, I've made it raise an error rather than silently doing something stupid ;-)

### CODE REVIEW

**Comment by tserong** [comment]
Marked DNM as I'm waiting for a build so I can do a proper clean test.

**Review by sallen-suse — APPROVED** [review]
LGTM

**Review by mgfritch — APPROVED** [review]
awesome! Thanks @tserong

**Comment by tserong** [comment]
Tested with:

```
# ceph orch upgrade registry.suse.de/home/tserong/branches/devel/storage/7.0/pacific/containers/ses/7.1/ceph/ceph
# ceph config rm global container_image
# ceph orch redeploy mds.cephfs
```

After redeploying the MDS, verified it was using registry.suse.com/ses/7.1/ceph/ceph:latest instead of docker.io/ceph/daemon-base:latest-pacific-devel (which is what it would have used previously).

**Pull request merged**
