### PR TITLE
librgw: initialize curl and http client for multisite

### PR DESCRIPTION
**Pull request by theanalyst**
bsc#1110415
(will require nfs-ganesha update with librgw)

--
Fixes: http://tracker.ceph.com/issues/36302

Signed-off-by: Casey Bodley <cbodley@redhat.com>
(cherry picked from commit 1d44ba04513e06978fa1e3115ebb86292d625df4)

### CODE REVIEW

**Comment by theanalyst** [comment]
@kshtsk @smithfarm not sure why ci is reporting a failure on this one.

**Comment by kshtsk** [comment]
@smithfarm is that okay that there compilation errors or they are not related?

**Comment by kshtsk** [comment]
```[ 96%] Building CXX object src/test/rgw/CMakeFiles/unittest_rgw_iam_policy.dir/test_rgw_iam_policy.cc.o
/opt/j/ws/mkck/src/rgw/librgw.cc: In member function ‘int rgw::RGWLib::init(std::vector<const char*>&)’:
/opt/j/ws/mkck/src/rgw/librgw.cc:495:40: error: ‘rgw_http_client_init’ was not declared in this scope
     rgw_http_client_init(g_ceph_context);
                                        ^
/opt/j/ws/mkck/src/rgw/librgw.cc: In member function ‘int rgw::RGWLib::stop()’:
/opt/j/ws/mkck/src/rgw/librgw.cc:605:29: error: ‘rgw_http_client_cleanup’ was not declared in this scope
     rgw_http_client_cleanup();
                             ^
src/rgw/CMakeFiles/rgw.dir/build.make:62: recipe for target 'src/rgw/CMakeFiles/rgw.dir/librgw.cc.o' failed
make[3]: *** [src/rgw/CMakeFiles/rgw.dir/librgw.cc.o] Error 1
```

**Comment by smithfarm** [comment]
@theanalyst When you click on "Details", you'll get a Jenkins login page. If you don't have the Jenkins credentials, ask @kshtsk or myself on IRC.

**Comment by kshtsk** [comment]
@theanalyst @smithfarm if there is a login page on the log page for this PR, it is Jenkins issue, let me know, no login pages should be required for ci logs.

**Comment by theanalyst** [comment]
@kshtsk it only leads to login page for me

**Comment by theanalyst** [comment]
I realize what is happening now, the default vstart target didn't build `librgw` so this was uncaught in my local setup. fixed now

**Comment by theanalyst** [comment]
@smithfarm @kshtsk I see the current failures in other builds as well (the earlier error has been fixed)

**Comment by kshtsk** [comment]
retest this please

**Comment by theanalyst** [comment]
updated, this and https://github.com/SUSE/ceph/pull/213 should pref. go in together

**Pull request merged**
