### PR TITLE
qa/tasks: support '-' in array_to_json

### PR DESCRIPTION
**Pull request by kshtsk**
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@gmail.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
http://10.86.4.15/teuthology/runner-2019-04-17_16:30:08-suse-ses6---basic-ecp/75/teuthology.log
```
2019-04-17T17:03:32.034 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:+++ array_to_json target-mainstream-094
2019-04-17T17:03:32.035 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:+++ array=("$@")
2019-04-17T17:03:32.035 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:+++ local array
2019-04-17T17:03:32.035 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:+++ result='['
2019-04-17T17:03:32.036 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:++++ echo target-mainstream-094
2019-04-17T17:03:32.036 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:++++ sed 's/\([^ \t]\+\)/"\1"/g'
2019-04-17T17:03:32.036 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:++++ sed 's/[ \t]\+/, /g'
2019-04-17T17:03:32.038 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:+++ result+='"target-mainstream-094"'
2019-04-17T17:03:32.039 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:+++ result+=']'
2019-04-17T17:03:32.039 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:+++ echo '["target-mainstream-094"]'
2019-04-17T17:03:32.040 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:++ create_cephfs_export /test1 '["target-mainstream-094"]'
2019-04-17T17:03:32.040 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:++ local path=/test1
2019-04-17T17:03:32.040 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:++ local 'daemons=["target-mainstream-094"]'
2019-04-17T17:03:32.040 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:++ cat
2019-04-17T17:03:32.043 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:++++ cat /tmp/export.json
2019-04-17T17:03:32.045 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:+++ rest_call POST /api/nfs-ganesha/export '{
2019-04-17T17:03:32.046 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:  "cluster_id": "_default_",
2019-04-17T17:03:32.046 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:  "path": "/test1",
2019-04-17T17:03:32.046 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:  "fsal": {
2019-04-17T17:03:32.047 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:    "name": "CEPH",
2019-04-17T17:03:32.047 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:    "user_id": "admin",
2019-04-17T17:03:32.047 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:    "fs_name": "cephfs",
2019-04-17T17:03:32.048 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:    "sec_label_xattr": null
2019-04-17T17:03:32.048 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:  },
2019-04-17T17:03:32.048 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:  "pseudo": "/cephfs/test1",
2019-04-17T17:03:32.048 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:  "tag": null,
2019-04-17T17:03:32.048 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:  "access_type": "RW",
2019-04-17T17:03:32.048 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:  "squash": "no_root_squash",
2019-04-17T17:03:32.049 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:  "protocols": [3, 4],
2019-04-17T17:03:32.049 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:  "transports": ["TCP"],
2019-04-17T17:03:32.049 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:  "security_label": false,
2019-04-17T17:03:32.049 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:  "daemons": ["target-mainstream-094"],
2019-04-17T17:03:32.049 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:  "clients": []
2019-04-17T17:03:32.049 INFO:teuthology.orchestra.run.target-mainstream-080.stderr:}'

```

**Comment by kshtsk** [comment]
retest this please

**Comment by smithfarm** [comment]
The issue here is that `array_to_json`, as it is currently implemented, does not clearly separate each array element - this is because it relies on an "echo" statement instead of looping over the array elements.

For testing, I created a bash array like so: `ARRAY=(one two-fer three '18*' 'goodbye, Marianne')`

Without this patch, `array_to_json` failed miserably on this array:

```
$ bash ~/test.sh
["one", "two"-"fer", "three", "18"*, "goodbye",, "Marianne"]
```

With the patch, it does a better job, but still chokes on the last one because it treats spaces as separators between elements:

```
$ bash ~/test.sh
["one", "two-fer", "three", "18*", "goodbye,", "Marianne"]
```

However, this is good enough for our purposes here, because the array will only contain hostnames, and those are guaranteed to not contain whitespace.

**Comment by smithfarm** [comment]
Test run demonstrating that the patch will not break the CI: http://10.86.0.135:8081/ubuntu-2019-04-18_10:07:51-deepsea:tier2:nfs-ganesha-ses6-fix-array_to_json---basic-openstack/

**Comment by kshtsk** [comment]
> However, this is good enough for our purposes here, because the array will only contain hostnames, and those are guaranteed to not contain whitespace.

I would not use the 'sed' for converting an array to json at all, but it will take much more time and lines of code.

**Pull request merged**
