### PR TITLE
qa/deepsea: migrate from storage profiles to drive groups 

### PR DESCRIPTION
**Pull request by smithfarm**

### CODE REVIEW

**Comment by jschmid1** [comment]
looks good. I may have missed it, but we need an explicit 'role-storage' in the policy.cfg now.

**Comment by jschmid1** [comment]
> looks good. I may have missed it, but we need an explicit 'role-storage' in the policy.cfg now.

Ah, it's there my bad. LGTM then

**Comment by smithfarm** [comment]
@jschmid1 Please merge this one at the same time as you merge https://github.com/SUSE/DeepSea/pull/1517

Later, we'll need to roll it out to the `ses6` branch in coordination with the next DeepSea release.

**Comment by jschmid1** [comment]
> @jschmid1 Please merge this one at the same time as you merge [SUSE/DeepSea#1517](https://github.com/SUSE/DeepSea/pull/1517)
> 
> Later, we'll need to roll it out to the `ses6` branch in coordination with the next DeepSea release.

Yikes, I forgot about that..

**Comment by smithfarm** [comment]
@jschmid1 See https://github.com/SUSE/ceph/pull/276

**Pull request merged**
