### PR TITLE
Wip v12.0.2

### PR DESCRIPTION
**Pull request by smithfarm**
This brings in @ddiss 's commit a41a8a9 and updates the product to upstream `v12.0.2` tag

### CODE REVIEW

**Comment by smithfarm** [comment]
Test build running here: https://build.suse.de/package/show/Devel:Storage:5.0:Staging:Testing/ceph

**Comment by ddiss** [comment]
looks like a crypto library is failing to build:
[ 1712s] src/crypto/isa-l/CMakeFiles/ceph_crypto_isal.dir/build.make:452: recipe for target 'lib/libceph_crypto_isal.so.1.0.0' failed
[ 1712s] make[2]: *** [lib/libceph_crypto_isal.so.1.0.0] Error 1
[ 1712s] CMakeFiles/Makefile2:20005: recipe for target 'src/crypto/isa-l/CMakeFiles/ceph_crypto_isal.dir/all' failed

**Comment by theanalyst** [comment]
CERN also reported a mon. crash on upgrade, we might need to  pull this as well https://github.com/ceph/ceph/pull/14442 , Let me see if I can get an approval for 12.0.3

**Comment by smithfarm** [comment]
@theanalyst Brought it up to 0d368d2 which includes both https://github.com/ceph/ceph/pull/14442 and https://github.com/ceph/ceph/pull/14721

**Comment by ddiss** [comment]
libceph_crypto_isal is still causing build failures on non-x86_64 platforms.

**Comment by theanalyst** [comment]
@ddiss won't 14721 not include isa-l at all?

**Comment by ddiss** [comment]
> @ddiss won't 14721 not include isa-l at all?

You're right, that should address the failure.... I guess I was looking at an out-of-date build log.

**Comment by smithfarm** [comment]
@ddiss I was wondering how you build-tested it so fast? ;-)

**Comment by smithfarm** [comment]
New test-build running at https://build.suse.de/package/show/Devel:Storage:5.0:Staging:Testing/ceph

**Comment by smithfarm** [comment]
The latest FTBFS is addressed by https://github.com/ceph/ceph/pull/14779

**Comment by smithfarm** [comment]
The last patch fixes the build and is on-track to be merged upstream, so I'm merging this now.

**Pull request merged**
