### PR TITLE
Merge upstream v12.0.3 tag into ses5

### PR DESCRIPTION
**Pull request by smithfarm**
Asking @ddiss to review conflict resolution in `src/test/librados/c_write_operations.cc` - see the conflict resolution description in the merge commit https://github.com/SUSE/ceph/pull/114/commits/07538d4860d792131141424153ebede22a71b934

### CODE REVIEW

**Comment by smithfarm** [comment]
Test build running at https://build.suse.de/package/show/Devel:Storage:5.0:Staging:Testing/ceph

**Comment by smithfarm** [comment]
```
[  158s] CMake Error at src/dmclock/CMakeLists.txt:20 (find_package):
[  158s]   By not providing "Findgtest.cmake" in CMAKE_MODULE_PATH this project has
[  158s]   asked CMake to find a package configuration file provided by "gtest", but
[  158s]   CMake did not find one.
[  158s] 
[  158s]   Could not find a package configuration file provided by "gtest" with any of
[  158s]   the following names:
[  158s] 
[  158s]     gtestConfig.cmake
[  158s]     gtest-config.cmake
[  158s] 
[  158s]   Add the installation prefix of "gtest" to CMAKE_PREFIX_PATH or set
[  158s]   "gtest_DIR" to a directory containing one of the above files.  If "gtest"
[  158s]   provides a separate development package or SDK, be sure it has been
[  158s]   installed.
[  158s] 
[  158s] 
[  158s] -- Configuring incomplete, errors occurred!
```

**Comment by smithfarm** [comment]
Added a commit to address the build failure, also submitted upstream at https://github.com/ceph/ceph/pull/15174

Re-running test build.

**Comment by smithfarm** [comment]
googletest is built as a submodule, and FindGMake.cmake was failing the build because it couldn't find libgtest. Kefu suggested to point cmake at the submodule by setting the GTEST_ROOT environment variable. Trying that now.

**Comment by smithfarm** [comment]
@rjfd The last two commits (taken from https://github.com/ceph/ceph/pull/15174) fix the `ceph.spec` build, but the `ceph-test.spec` build is still broken. Quoting from https://build.suse.de/public/build/Devel:Storage:5.0:Staging:Testing/SLE12_SP3/x86_64/ceph-test/_log

```
[  978s] [ 43%] Linking CXX executable ../../../bin/dmclock-tests
[  978s] ../../../lib/libgtest.a(gtest-all.cc.o): In function `~ThreadLocal':
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2040: undefined reference to `pthread_getspecific'
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2044: undefined reference to `pthread_key_delete'
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2040: undefined reference to `pthread_getspecific'
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2044: undefined reference to `pthread_key_delete'
[  978s] ../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<testing::TestPartResultReporterInterface*>::CreateKey()':
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2070: undefined reference to `pthread_key_create'
[  978s] ../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<std::vector<testing::internal::TraceInfo, std::allocator<testing::internal::TraceInfo> > >::CreateKey()':
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2070: undefined reference to `pthread_key_create'
[  978s] ../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<std::vector<testing::internal::TraceInfo, std::allocator<testing::internal::TraceInfo> > >::GetOrCreateValue() const':
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2077: undefined reference to `pthread_getspecific'
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2084: undefined reference to `pthread_setspecific'
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2077: undefined reference to `pthread_getspecific'
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2084: undefined reference to `pthread_setspecific'
[  978s] ../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<testing::TestPartResultReporterInterface*>::GetOrCreateValue() const':
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2077: undefined reference to `pthread_getspecific'
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2084: undefined reference to `pthread_setspecific'
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2077: undefined reference to `pthread_getspecific'
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2084: undefined reference to `pthread_setspecific'
[  978s] ../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<std::vector<testing::internal::TraceInfo, std::allocator<testing::internal::TraceInfo> > >::GetOrCreateValue() const':
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2077: undefined reference to `pthread_getspecific'
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2084: undefined reference to `pthread_setspecific'
[  978s] ../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<std::vector<testing::internal::TraceInfo, std::allocator<testing::internal::TraceInfo> > >::~ThreadLocal()':
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2040: undefined reference to `pthread_getspecific'
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2044: undefined reference to `pthread_key_delete'
[  978s] ../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<testing::TestPartResultReporterInterface*>::~ThreadLocal()':
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2040: undefined reference to `pthread_getspecific'
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2044: undefined reference to `pthread_key_delete'
[  978s] ../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<std::vector<testing::internal::TraceInfo, std::allocator<testing::internal::TraceInfo> > >::GetOrCreateValue() const':
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2077: undefined reference to `pthread_getspecific'
[  978s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/src/googletest/googletest/include/gtest/internal/gtest-port.h:2084: undefined reference to `pthread_setspecific'
[  978s] collect2: error: ld returned 1 exit status
[  978s] src/dmclock/test/CMakeFiles/dmclock-tests.dir/build.make:175: recipe for target 'bin/dmclock-tests' failed
```

This makes no sense to me, since `pthread` is included in the `target_link_libraries()` call for dmclock-tests!

**Comment by smithfarm** [comment]
It gets worse. The boost submodule (1.63 apparently) fails to build on s390x:

```
[  121s] libs/context/src/unsupported.cpp:7:2: error: #error "platform not supported"
[  121s]  #error "platform not supported"
[  121s]   ^
[  164s] ...skipped <p/home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/build/boost-build/boost/bin.v2/libs/context/build/gcc-4.8/release/link-static/threading-multi>libboost_context.a(clean) for lack of <p/home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/build/boost-build/boost/bin.v2/libs/context/build/gcc-4.8/release/link-static/threading-multi>unsupported.o...
[  164s] ...skipped <p/home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/build/boost-build/boost/bin.v2/libs/context/build/gcc-4.8/release/link-static/threading-multi>libboost_context.a for lack of <p/home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/build/boost-build/boost/bin.v2/libs/context/build/gcc-4.8/release/link-static/threading-multi>unsupported.o...
[  164s] ...skipped <p/home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/build/boost/lib>libboost_context.a for lack of <p/home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1495217527.9b626e3f69/build/boost-build/boost/bin.v2/libs/context/build/gcc-4.8/release/link-static/threading-multi>libboost_context.a...
[  196s] ...failed updating 1 target...
[  196s] CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:725 (message):
[  196s]   Imported targets not available for Boost version 106300
[  196s] Call Stack (most recent call first):
[  196s]   /usr/share/cmake/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
[  196s]   /usr/share/cmake/Modules/FindBoost.cmake:1315 (_Boost_MISSING_DEPENDENCIES)
[  196s]   CMakeLists.txt:594 (find_package)
```

**Comment by smithfarm** [comment]
Interestingly, the pthread failure is not reproduced in the upstream build: https://shaman.ceph.com/builds/ceph/wip-findgtest-cmake/

**Comment by kshtsk** [comment]
retest this please

**Comment by smithfarm** [comment]
Note this PR does not build in OBS, so make check might fail too.

**Comment by smithfarm** [comment]
c9169a7 builds are all green except on s390x.

Added three more commits in a bid to fix the s390x build as well.

**Comment by kshtsk** [comment]
Package 'rdma-core-devel' not found.

**Comment by smithfarm** [comment]
> Package 'rdma-core-devel' not found.

It's there (in the SDK). Note that there was a bug [1] in that it was impossible to install, but that has since been fixed.

[1] https://bugzilla.suse.com/show_bug.cgi?id=1040159

**Comment by smithfarm** [comment]
This PR has been superseded by #115 but I'll leave it open until that one is merged.

**Pull request closed without merging**
