### PR TITLE
Deactivate Java in SUSE; saner LLTng enablement

### PR DESCRIPTION
**Pull request by smithfarm**

### CODE REVIEW

**Comment by smithfarm** [comment]
@ddiss @kmroz @tserong

**Comment by smithfarm** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;183LeQFa&#x2F;1946-ses2-1-deactivate-java-in-suse-saner-lltng-enablement"> (SES2.1) Deactivate Java in SUSE; saner LLTng enablement</a>

**Comment by tserong** [comment]
LGTM

**Comment by smithfarm** [comment]
Deactivating Java in the spec file (as opposed to by Project Config macro, as we're doing it now) has the disadvantage that it breaks teuthology. This is because teuthology has a list of ceph packages it installs on all test nodes, and this list includes the cephfs-java packages.

**Comment by tserong** [comment]
That's unfortunate :-/ Um... Can teuthology be made to just kinda try to install cephfs-java, but not care if it's not there...?

**Comment by smithfarm** [comment]
I will patch the packages list in ceph-qa-suite hammer branch so it doesn't install the java packages. The java tests will fail, obviously, but this is the least disruptive solution I can think of.

**Comment by smithfarm** [comment]
rebased

**Comment by smithfarm** [comment]
Triggered test build in https://build.suse.de/package/show/home:smithfarm:SES2:test1/ceph

**Pull request merged**
