### PR TITLE
cephadm: update to the latest container images

### PR DESCRIPTION
**Pull request by mgfritch**
- prometheus-server:2.37.6
- prometheus-node-exporter:1.5.0
- grafana:9.5.5
- haproxy:2.0.31

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tserong** [comment]
I've reviewed the available container image versions on registry.suse.com (via `skopeo inspect`), and it looks like the newest we've got there are:

- registry.suse.com/ses/7.1/ceph/prometheus-server:2.32.1 (old)
- registry.suse.com/ses/7.1/ceph/prometheus-node-exporter:1.5.0 (fine)
- registry.suse.com/ses/7.1/ceph/grafana:8.5.22 (old)
- registry.suse.com/ses/7.1/ceph/haproxy:2.0.31 (fine)

The newer version in this PR _are_ in our internal registry in our devel project:

- registry.suse.de/devel/storage/7.0/pacific/containers/ses/7.1/ceph/prometheus-server:2.37.6
- registry.suse.de/devel/storage/7.0/pacific/containers/ses/7.1/ceph/prometheus-node-exporter:1.5.0
- registry.suse.de/devel/storage/7.0/pacific/containers/ses/7.1/ceph/grafana:9.5.5
- registry.suse.de/devel/storage/7.0/pacific/containers/ses/7.1/ceph/haproxy:2.0.31

..and are also in the SES 7.1 update project:

- registry.suse.de/suse/sle-15-sp3/update/products/ses7/update/cr/containers/ses/7.1/ceph/prometheus-server:2.37.6
- registry.suse.de/suse/sle-15-sp3/update/products/ses7/update/cr/containers/ses/7.1/ceph/prometheus-node-exporter:1.5.0
- registry.suse.de/suse/sle-15-sp3/update/products/ses7/update/cr/containers/ses/7.1/ceph/grafana:9.5.5
- registry.suse.de/suse/sle-15-sp3/update/products/ses7/update/cr/containers/ses/7.1/ceph/haproxy:2.0.31

So we need to get prometheus-server:2.37.6 and grafana:9.5.5 published to registry.suse.com before this PR will work. I'm happy to request those two be published, but would like to get an OK from @s0nea first.

**Comment by s0nea** [comment]
> I'm happy to request those two be published, but would like to get an OK from @s0nea first.

Thank you for taking care of it! I'll post my update to the PR once I'm done with testing.

**Comment by s0nea** [comment]
I did some testing.

- **prometheus-server:2.37.6**
- **prometheus-node-exporter:1.5.0**
are both looking fine.

For the Grafana image I suggest to use **grafana:8.5.22** instead of **grafana:9.5.5**. The pie-chart plugin doesn't seem to work well with version 9.5.5.

**Review by s0nea — COMMENTED** [review]
LGTM - thank you!

I don't approve the PR because I suggest to wait for @tserong to confirm that the images have been published on the registry. Once done you can count my comment as an approval :slightly_smiling_face:

**Comment by tserong** [comment]
The images are all there now, so we're good:

```
> for i in registry.suse.com/ses/7.1/ceph/prometheus-server:2.37.6 registry.suse.com/ses/7.1/ceph/prometheus-node-exporter:1.5.0 registry.suse.com/ses/7.1/ceph/grafana:8.5.22 registry.suse.com/ses/7.1/ceph/haproxy:2.0.31 ; do podman pull $i ; done
Trying to pull registry.suse.com/ses/7.1/ceph/prometheus-server:2.37.6...
Getting image source signatures
[...]
Writing manifest to image destination
Storing signatures
dcfeac85d41459a41e04da6daad95dd3b8832bcd5ec65659b0a5c95a066bddde
Trying to pull registry.suse.com/ses/7.1/ceph/prometheus-node-exporter:1.5.0...
Getting image source signatures
[...]
Writing manifest to image destination
Storing signatures
155394da0b9d6150dfcb21abe289d4846ac6e2c66bd4cd519d9a05489952650c
Trying to pull registry.suse.com/ses/7.1/ceph/grafana:8.5.22...
Getting image source signatures
[...]
Writing manifest to image destination
Storing signatures
b2e3ade90b30fe398984e602825aa48649b85d048b578abdd42720934676efc7
Trying to pull registry.suse.com/ses/7.1/ceph/haproxy:2.0.31...
Getting image source signatures
[...]
Writing manifest to image destination
Storing signatures
40724cbe8af0cbae6b8f1f92e8d80e2d90168b1f7670de91916e388a4eae4f5e
```

**Pull request merged**
