### PR TITLE
SUSE branding for the ceph dashboard

### PR DESCRIPTION
**Pull request by Exotelis**
Hi

Here are the changes for the SUSE ceph dashboard branding.
The only file that could conflict is the `angular.json`. We should discuss who is responsible for resolving conflicts if they happen.

### CODE REVIEW

**Comment by kshtsk** [comment]
@smithfarm make check failure:
```09:39:47 CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
09:39:47   Could NOT find RabbitMQ (missing: rabbitmq_INCLUDE_DIR rabbitmq_LIBRARY)
09:39:47 Call Stack (most recent call first):
09:39:47   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
09:39:47   cmake/modules/FindRabbitMQ.cmake:9 (find_package_handle_standard_args)
09:39:47   src/CMakeLists.txt:295 (_find_package)
09:39:47   src/rgw/CMakeLists.txt:207 (find_package)
```

**Comment by Exotelis** [comment]
@kshtsk had the same issue on my dev environment using tumbleweed. For tumbleweed I fixed this by running: 

```
zypper addrepo https://download.opensuse.org/repositories/home:jbrielmaier/openSUSE_Tumbleweed/home:jbrielmaier.repo
zypper ref
zypper in rabbitmq-c rabbitmq-c-devel
```

**Comment by smithfarm** [comment]
Thanks @Exotelis - don't worry about the make check failure.

**Comment by smithfarm** [comment]
Note: I will keep this PR open, but apply the commits manually for each product build. 

The purpose for keeping the PR open is: I am still rebasing ses6 periodically, so if any conflicts appear, they will show up here in the PR.

**Comment by kshtsk** [comment]
retest this please

**Comment by Exotelis** [comment]
Updated the branding template of the navigation to add the missing NFS menu item. Also rebased with `34f04be`

**Comment by smithfarm** [comment]
If nobody objects, I will close this PR in favor of https://github.com/SUSE/ceph/pull/285 (which will be used for tracking **all** downstream commits, not just the dashboard branding ones)

**Comment by kshtsk** [comment]
> If nobody objects, I will close this PR in favor of #285 (which will be used for tracking **all** downstream commits, not just the dashboard branding ones)

I'm not sure this question is to me, but for the case I don't mind.

**Pull request closed without merging**
