### PR TITLE
qa/deepsea: harvest logs from Dashboard E2E tests 

### PR DESCRIPTION
**Pull request by smithfarm**

### CODE REVIEW

**Comment by callithea** [comment]
Is ``.protractor-report/index.html`` somewhere available after running the tests?

**Comment by smithfarm** [comment]
@callithea Now it is ;-)

Note that the logs are harvested only if the test fails. So we'd have to introduce a failing E2E test to see if this actually works...

**Comment by kshtsk** [comment]
> @callithea Now it is ;-)
> 
> Note that the logs are harvested only if the test fails. So we'd have to introduce a failing E2E test to see if this actually works...

I would like to grab test results always, can we implement this?

**Comment by kshtsk** [comment]
> > @callithea Now it is ;-)
> > Note that the logs are harvested only if the test fails. So we'd have to introduce a failing E2E test to see if this actually works...
> 
> I would like to grab test results always for e2e, can we implement this?

or have an option? or maybe there is an option already to force it harvest log, for example via overrides?

**Comment by smithfarm** [comment]
@callithea Harvesting logs on all runs (including successful one) would quickly fill up the disk on the teuthology server, I would think.

I'm not aware of any option to force log harvesting, but it would certainly be possible to implement one.

**Comment by kshtsk** [comment]
@smithfarm on jenkins we do not store logs forever, similar strategy can be used for teuthology.

**Comment by smithfarm** [comment]
Anyway, we want to use the same teuthology code as upstream, right? I don't think upstream would agree to harvest logs from all successful runs...

**Comment by smithfarm** [comment]
Keep in mind that if we harvest logs from both successful and failed test runs, the available disk space for log storage will be filled primarily with logs from successful runs. We can implement pruning (delete the older logs when the disk space starts to fill up) but even then - if 95% of the jobs finish successfully, 95% of the available storage for logs will be filled with successful logs. This does not make much sense IMO.

**Comment by kshtsk** [comment]
> Keep in mind that if we harvest logs from both successful and failed test runs, the available disk space for log storage will be filled primarily with logs from successful runs. We can implement pruning (delete the older logs when the disk space starts to fill up) but even then - if 95% of the jobs finish successfully, 95% of the available storage for logs will be filled with successful logs. This does not make much sense IMO.

I do not insist this feature within this patch, but for downstream we can prune all logs older a week or month for example, and only for e2e test reports, no system logs.

**Comment by smithfarm** [comment]
http://51.68.82.180:8081/runner-2019-07-10_14:01:18-suse:tier2:dashboard-e2e-ses6-none-basic-ovh/

**Pull request merged**
