### PR TITLE
Re-implement ceph-disk deprecation warning (less strident)

### PR DESCRIPTION
**Pull request by smithfarm**
I don't think there will be many changes to ceph-disk in mimic, so the risk of carrying this luminous-only commit in downstream SES6 is low.

What do you think?

### CODE REVIEW

**Comment by smithfarm** [comment]
Sorry if I left anyone out - any and all reviews are welcome.

**Comment by smithfarm** [comment]
These deprecation warnings are really obnoxious, and with most (all?) users not coming into direct contact with ceph-disk I don't see any reason to blare these warnings out all the time.

**Comment by smithfarm** [comment]
@jan--f Good point. When I think about it more, it's the form of the warning that bothers me, not the substance. I'll re-do this to retain the warning but tone its intensity down 15 or so notches.

**Comment by smithfarm** [comment]
@jan--f How is this looking to you?

**Comment by jan--f** [comment]
@smithfarm Look alright to me. Not trying to draw this out unnecessarily but personally I would have put in SOME ALL CAPS message, but that should not stop this PR.

**Comment by smithfarm** [comment]
Regarding downstream tickets, we do have https://github.com/SUSE/DeepSea/issues/747

**Comment by smithfarm** [comment]
changes applied to ses6 manually

**Pull request closed without merging**
