### PR TITLE
cephadm: use full qualified image names for cephadm

### PR DESCRIPTION
**Pull request by p-se**
To make the adoption of a Ceph cluster monitoring components use the
images.

Signed-off-by: Patrick Seidensal <pseidensal@suse.com>

We possibly want to wait with merging this PR until https://github.com/ceph/ceph/pull/36315 has been merged into the ses7 branch.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available @susebot commands</summary>

- `@susebot run make check`
- `@susebot run make check sles`
- `@susebot run make check leap`

</details>

### CODE REVIEW

**Review by sebastian-philipp — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
This is going to be a bit problematic when adopting clusters in air-gapped deployments. Is there any way to overwrite this?

**Comment by p-se** [comment]
The images to be used can be configured in cephadm, I don't know though, if those are considered by adopt. @swiftgist do you know if adopt can be told to use different images for adopting?

**Comment by swiftgist** [comment]
The adopt and create call the same container related functions, so github.com/ceph/ceph/blob/master/src/cephadm/cephadm#L5220-L5223 should apply?

**Comment by smithfarm** [comment]
I cherry-picked this one manually. Thanks!

**Comment by smithfarm** [comment]
UPDATE: It's actually https://github.com/ceph/ceph/pull/36975 that we're interested in, since it's the PR by which https://github.com/ceph/ceph/pull/36315 is being backported to `octopus`.

I'm assuming that, somehow or another, https://github.com/ceph/ceph/pull/36315 will get backported in time for M17.

**Pull request closed without merging**
