### PR TITLE
Update node-exporter container image

### PR DESCRIPTION
**Pull request by p-se**
Signed-off-by: Patrick Seidensal <pseidensal@suse.com>

Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1192875

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by p-se** [comment]
Giving it a second thought, it might need to be accompanied with a documentation upgrade. I dimly remember having the present versions mentioned there, too. I'll check that.

**Comment by smithfarm** [comment]
@p-se Would it make sense to open a Bugzilla for this?

**Review by ml8mr — APPROVED** [review]
LGTM, although I wonder why the older image was removed. I didn't think we did that...

**Comment by tserong** [comment]
Our documentation refers to registry.suse.com/caasp/v4.5/prometheus-node-exporter:0.18.1 (not 0.17.0), and 0.18.1 _is_ available in registry.suse.com. Should we prefer this earlier version rather than a bump to 1.0.1?

**Review by tserong — CHANGES_REQUESTED** [review]
Our documentation refers to registry.suse.com/caasp/v4.5/prometheus-node-exporter:0.18.1 (not 0.17.0), see:

https://documentation.suse.com/ses/7/single-html/ses-deployment/index.html#id-1.3.4.5.4.13.4.4.7.5
https://documentation.suse.com/ses/7/single-html/ses-admin/#monitoring-custom-images

...and 0.18.1 _is_ available in registry.suse.com. I also went back and checked the very first cephadm RPM we released with SES7 (cephadm-15.2.5.514+g7a2bcdb091-1.1.x86_64.rpm), and that _also_ uses registry.suse.com/caasp/v4.5/prometheus-node-exporter:0.18.1.

I have to assume that we somehow reverted incorrectly to 0.17.0 at some point in the ses7 branch. Under the circumstances, shouldn't we switch it back to 0.18.1 rather than taking a (large?) bump to 1.0.1?

**Comment by tserong** [comment]
Aha! The earliest mention of 0.18.1 I can find is https://github.com/SUSE/ceph/commit/a75e74c1874 in the ses7-mu1 branch (that's from November 2020. That same change is still there in the ses7-mu8 branch (https://github.com/SUSE/ceph/commit/68054702885), but is not present in the latest ses7 or ses7-mu9 branch. Instead, we have https://github.com/SUSE/ceph/commit/619ee62fd33, which is what introduced the change from 0.18.1 to 0.17.0, a couple of weeks ago.

**Comment by smithfarm** [comment]
Thanks, Tim! I see what happened now. Here's what I think happened play-by-play:

1. https://github.com/SUSE/ceph/pull/401 was opened containing the commit "cephadm: use full qualified image names for cephadm" in this original form: https://github.com/SUSE/ceph/pull/401/commits/273ab431cf78ccdc80a7b7b7b6dad47ef847f935
2. since ses7 got rebased in the meantime, I couldn't merge PR #401 so I just cherry-picked that one commit. At this point the node-exporter version was 0.17.0 (but from v5 of CaaSP)
3. https://github.com/SUSE/ceph/pull/411 was opened containing the commit "Switch to CaaSP v4.5 container images" in this original form: https://github.com/SUSE/ceph/pull/411/commits/8e915845164d88e70e56fc472764148e50d53fa3
4. PR #411 got merged into ses7. This changed the node-exporter version to 0.18.1 (from CaaSP v4.5)
5. everything was fine for a long time...
6. upstream released 15.2.15, which touches the code in question
7. ses7 got rebased on top of 15.2.15 - during this rebase I presumably got conflicts in these two commits, and I resolved the conflicts incorrectly

To fix this, I will:

1. drop the two offending commits 9f2a6c6ce8d and 619ee62fd33 from ses7 and ses7-mu9
2. open a new PR with a "proper" cherry-pick of these two commits. Once that PR is merged, this PR (update of node-exporter container image to 1.0.1) can be rebased.

**Comment by smithfarm** [comment]
Update to the previous comment:

https://github.com/SUSE/ceph/pull/446 is open to get a clean base for this PR.

**Review by smithfarm — CHANGES_REQUESTED** [review]
Needs rebase, preferably after #446 is merged.

**Comment by tserong** [comment]
Do we need this PR at all anymore, since #446 is merged? The original problem was that node exporter 0.17.0 didn't exist. That's fixed now that we're back on 0.18.1. Or is there some other additional reason to update to 1.0.1?

**Comment by p-se** [comment]
No, there's no urgent need to do the upgrade now. As there are images in the pipeline that change the namespace from CaaSP to SES, I tend to wait for them to be included rather than upgrading now.

**Pull request closed without merging**
