### PR TITLE
Merge latest upstream master

### PR DESCRIPTION
**Pull request by smithfarm**

### CODE REVIEW

**Comment by smithfarm** [comment]
Test build running at https://build.suse.de/package/show/Devel:Storage:5.0:Staging:Testing/ceph

**Comment by smithfarm** [comment]
@rjfd Build fails due to RPATH issues. Marking DNM until we can re-fix it upstream.

**Comment by smithfarm** [comment]
Triggered another build at the same URL.

**Comment by smithfarm** [comment]
Astoundingly, this PR introduces this regression in s390x and ppc64le:

```
[  376s] [  4%] Performing forcebuild step for 'rocksdb_ext'
[  376s] [  4%] Performing build step for 'rocksdb_ext'
[  376s] Scanning dependencies of target build_version
[  376s] [  0%] Building CXX object CMakeFiles/build_version.dir/build_version.cc.o
[  376s] c++: error: unrecognized command line option '-momit-leaf-frame-pointer'
[  376s] CMakeFiles/build_version.dir/build.make:62: recipe for target 'CMakeFiles/build_version.dir/build_version.cc.o' failed
```

**Comment by smithfarm** [comment]
@rjfd Can you re-push the ceph-mgr RPATH patch - sorry, I lost it.

**Comment by rjfd** [comment]
@smithfarm I pushed a fix for the build, can you trigger a build?

**Comment by rjfd** [comment]
@smithfarm ppc64 and s390x builds are still failing due to this commit https://github.com/ceph/rocksdb/commit/c03a80edf5056faaeb13a24c4fecf4bfbe32066d not being in the master branch of ceph/rocksdb but rather in the wip-rocksdb

**Comment by smithfarm** [comment]
@rjfd There must have been a regression, because this PR [1] already fixed the issue 18 days ago (tested at the time).

[1] https://github.com/ceph/ceph/pull/12908

**Comment by rjfd** [comment]
@smithfarm the problem is that the commits to the rocksdb submodule from the PR https://github.com/ceph/ceph/pull/12908 were not pushed to the rocksdb master branch, but instead they were pushed to the wip-rocksdb branch.

If you check the rocksdb master branch commit log, you will see that those commits were never pushed.

**Comment by smithfarm** [comment]
@rjfd I see the problem now, and it's the same old regression as always. Kefu's PR https://github.com/ceph/ceph/pull/12908 added a commit 478c844b815e5d3cd5bed6cffc81b02e5ac15180 that updated the `src/rocksdb` submodule to `Subproject commit a9b0a54f4925a5a48c70fc19257af988acebcea9` which worked for a time, but then someone deleted the ceph/rocksdb branch containing that commit and it is no longer present in the tree. Possibly at the same time, https://github.com/ceph/ceph/pull/12992 was merged, updating `src/rocksdb` to a0deec960f3a8190831c673e5ba998fe6fb7ea90

So this is a regression. I will ping Kefu about it.

**Comment by smithfarm** [comment]
@rjfd Pushed Kefu's rocksdb fix and have another build running.

**Pull request merged**
