### PR TITLE
rpm: expand log file reown for ceph-radosgw

### PR DESCRIPTION
**Pull request by smithfarm**
Analogous change to d8f5376fef0cc0e0fb492651e85650a240e5b63f

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
Needs to be cherry-picked to `ses3` as well.

**Comment by smithfarm** [comment]
Note that the `logrotate.conf` fix applies only to `/var/lib/ceph/*.log` - we need to fix that.

**Comment by smithfarm** [comment]
@kmroz Do you know if RGW really does log to `/var/log/ceph-radosgw/*` by default (or as set up by ceph-deploy/DeepSea) in SES3/4? If so, would it make sense to change it to something like `/var/log/ceph/radosgw.log`?

**Comment by tserong** [comment]
I thought `/var/log/ceph-radosgw/` had somehow become obsolete/unused (was it ever used?). Anyway, the commit looks fine (it's a NOOP anyway if that dir isn't present).

**Comment by smithfarm** [comment]
The idea here is to drop a downstream-only patch that causes merge conflicts. My assumption is that, as of SES3, rgw is not logging to `/var/log/ceph-radosgw` even when deployed via ceph-deploy.

**Comment by kmroz** [comment]
@smithfarm - As per a quick test spooling up a SES3 cluster with ceph-deploy (also mentioned here: https://github.com/SUSE/ceph/pull/67#issuecomment-267718463), the RGW section in ceph.conf no longer specifies any custom log file location.  The same is true when deploying with DeepSea.  RGW will log to: `/var/log/ceph/ceph-<rgw_node_name>.log` as it should.

However, if someone skipped the upgrade script operation to standardize RGW logging location when upgrading from SES2.1 to SES3/4, they may still log to a custom location.

Otherwise, I think we can probably drop all `/var/log/ceph-radosgw` related stuff in SES3/SES4 and (as you have already done) in SES5.  Especially if that helps to avoid conflicts with upstream ceph.spec.

What do you guys think?  Or is it a bit risky?

**Comment by smithfarm** [comment]
@kmroz How long has the log file ownership fix been in the script? I thought it was only added recently?

I don't expect upstream to change the jewel spec file much anymore.

That said, I'm fine to drop it instead of fixing it.

**Comment by kmroz** [comment]
@smithfarm - The code for standardizing RGW logging location was added to the upgrade script prior to SES3 release.
```
54bbc30a src/upgrade-to-ses3.sh (Karol Mroz    2016-05-23 13:10:54 +0200  940) standardize_radosgw_logfile_location
```
The code to recursively chown /var/log/ceph was added more recently.

```
3a384845 src/upgrade-ses.sh     (Karol Mroz    2016-11-18 16:08:57 -0800  867) chown_var_log_ceph
```

So, the only problems I would expect from `/var/log/ceph-radosgw` related stuff would be for admins that skipped `standardize_radosgw_logfile_location` during an upgrade from 2.1 -> 3/4.  Which at the very least _is_ possible.

I'm for covering more bases... provided it doesn't cause you any grief when syncing down changes.

So, 👍 for this.  We're already removing all such things for SES5.

**Comment by smithfarm** [comment]
Yeah, might as well leave it in at this point - it does no harm. 

Cherry-picked to ses3.

**Pull request merged**
