### PR TITLE
SES3: merge v10.2.6 (656b5b6)

### PR DESCRIPTION
**Pull request by smithfarm**
This brings `ses3` to upstream 10.2.6 + various downstream patches from ses4.

The reviewer could please double-check that the following files are the same as in ses4:

```
    Conflicts: (all conflicts resolved in favor of what is in ses4)
            ceph.spec.in
            install-deps.sh
            qa/workunits/fs/test_python.sh
            qa/workunits/rados/test_python.sh
            qa/workunits/rbd/notify_master.sh
            qa/workunits/rbd/notify_slave.sh
            qa/workunits/rbd/rbd_mirror.sh
            qa/workunits/rbd/rbd_mirror_stress.sh
            qa/workunits/rbd/test_librbd_python.sh
            qa/workunits/rbd/test_lock_fence.sh
```

NOTE: Tested using the following bit of bash:

```
STUFF="ceph.spec.in
install-deps.sh
qa/workunits/fs/test_python.sh
qa/workunits/rados/test_python.sh
qa/workunits/rbd/notify_master.sh
qa/workunits/rbd/notify_slave.sh
qa/workunits/rbd/rbd_mirror.sh
qa/workunits/rbd/rbd_mirror_stress.sh
qa/workunits/rbd/test_librbd_python.sh
qa/workunits/rbd/test_lock_fence.sh
"
for x in $STUFF ; do
    git --no-pager diff ses4 -- $x
done
```

### CODE REVIEW

**Comment by smithfarm** [comment]
Build will appear here: https://build.suse.de/package/show/Devel:Storage:3.0:Staging/ceph

**Comment by smithfarm** [comment]
@kshtsk Can we turn the "make check" test off for ses3? Or is it expected to work?

**Comment by smithfarm** [comment]
passed a rados/basic run (10 of 10 jobs passed) on openSUSE 42.1

**Comment by kshtsk** [comment]
retest this please

**Comment by smithfarm** [comment]
@kshtsk I ran make check manually on `ses3` and it's failing `run-tox`. . . ISTR David fixed that, maybe the fix didn't get backported.

**Pull request merged**
