### PR TITLE
port civetweb https fix

### PR DESCRIPTION
**Pull request by kmroz**

### CODE REVIEW

**Comment by smithfarm** [comment]
@kmroz Let's open two upstream PRs for this so we can have them fixed in master as well as jewel. Going at it like this only fixes the issue in SES3 and SES4, so it'll come back and haunt us in SES5.

I went ahead and opened the upstream issue for the spec file fix - http://tracker.ceph.com/issues/16947 

Can you do the same for the civetweb NO_SSL_DL fix? Maybe there's already an upstream issue for that?

**Comment by smithfarm** [comment]
Upon closer examination, the spec file change is not needed because `libopenssl-devel` is the correct package name in SUSE. See http://tracker.ceph.com/issues/16947

**Comment by smithfarm** [comment]
So, the bug here is that some C++ code in civetweb is doing dlopen on the SSL library, and upstream has -DNO_SSL_DL for the C civetweb code, but not for the C++ code. Correct? Or is there more to it than that?

**Comment by smithfarm** [comment]
I *think* the issue was fixed for the CMake build here: https://github.com/ceph/ceph/commit/b451cbb3 (the commit message is good reading).

**Comment by kmroz** [comment]
We'll do this upstream.

**Comment by kmroz** [comment]
With the new move to drop autools by upstream, we're going back to our original plan of fixing this in our downstream branch

**Pull request merged**
