### PR TITLE
qa/tier1/health-ok: add prometheus and grafana roles

### PR DESCRIPTION
**Pull request by smithfarm**
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
I will test this manually before merging.

**Comment by smithfarm** [comment]
@jan--f @jschmid1 I tried this on deepsea 0.9.13+git.0.05225a458 (tip of DeepSea master, installed from the RPM that is in SES6 as of this writing) and the result is very interesting:

http://10.86.0.135:8081/ubuntu-2019-02-26_14:11:01-deepsea:tier1-wip-qa-promgraf---basic-openstack/

Summary:

* non-CLI passes
* CLI fails in Stage 2

The CLI test Stage 2 failure looks like this:

```
2019-02-26T14:29:38.360 INFO:teuthology.orchestra.run.target192168000004.stdout:[12/14] Executing state ceph.monitoring...
2019-02-26T14:29:40.104 INFO:teuthology.orchestra.run.target192168000004.stdout:         |_  select.minions(cluster=ceph, host=False)... ok
2019-02-26T14:29:40.936 INFO:teuthology.orchestra.run.target192168000004.stdout:         |_  select.minions(cluster=ceph, host=False)... ok
2019-02-26T14:29:41.833 INFO:teuthology.orchestra.run.target192168000004.stdout:         |_  select.minions(cluster=ceph, host=False)... ok
2019-02-26T14:29:42.583 INFO:teuthology.orchestra.run.target192168000004.stdout:         |_  select.minions(cluster=ceph, roles=rgw)... ok
2019-02-26T14:30:21.947 INFO:teuthology.orchestra.run.target192168000004.stdout:         |_  target192168000004.teuthology: golang-github-prometheus-prometheus ok
2019-02-26T14:30:22.171 INFO:teuthology.orchestra.run.target192168000004.stdout:         |_  target192168000004.teuthology: /etc/prometheus/prometheus.yml ok
2019-02-26T14:30:35.252 INFO:teuthology.orchestra.run.target192168000004.stdout:         |_  target192168000004.teuthology: /etc/prometheus/ses_nodes/target192168000004.teuthology.yml ok
2019-02-26T14:30:54.247 INFO:teuthology.orchestra.run.target192168000004.stdout:         |_  target192168000004.teuthology: golang-github-prometheus-alertmanager ok
2019-02-26T14:32:07.989 INFO:teuthology.orchestra.run.target192168000004.stdout:         |_  target192168000004.teuthology: grafana ok
2019-02-26T14:33:51.352 INFO:teuthology.orchestra.run.target192168000004.stdout:         target192168000004.teuthology... fail
2019-02-26T14:33:51.449 INFO:teuthology.orchestra.run.target192168000004.stdout:[13/14] Executing state ceph.monitoring.prometheus.exporters.node_exporter...
2019-02-26T14:34:12.980 INFO:teuthology.orchestra.run.target192168000004.stdout:         |_  target192168000004.teuthology: install node exporter package(golang-github-prometheus-node_exporter) ok
2019-02-26T14:34:33.269 INFO:teuthology.orchestra.run.target192168000004.stdout:         |_  target192168000004.teuthology: install smartmontools and cron packages ok
2019-02-26T14:34:48.805 INFO:teuthology.orchestra.run.target192168000004.stdout:         target192168000004.teuthology... ok
2019-02-26T14:34:49.472 INFO:teuthology.orchestra.run.target192168000004.stdout:[14/14] Executing runner advise.osds...
2019-02-26T14:34:49.472 INFO:teuthology.orchestra.run.target192168000004.stdout:         |_  osd.report(human=False)...
2019-02-26T14:34:49.678 INFO:teuthology.orchestra.run.target192168000004.stdout:               in target192168000004.teuthology... ok
2019-02-26T14:34:49.795 INFO:teuthology.orchestra.run.target192168000004.stdout:[14/14] Executing runner advise.osds... ok
2019-02-26T14:34:49.814 INFO:teuthology.orchestra.run.target192168000004.stdout:Finished stage ceph.stage.2: succeeded=13/14 failed=1/14
2019-02-26T14:34:49.815 INFO:teuthology.orchestra.run.target192168000004.stdout:
2019-02-26T14:34:49.815 INFO:teuthology.orchestra.run.target192168000004.stdout:Failures summary:
2019-02-26T14:34:49.815 INFO:teuthology.orchestra.run.target192168000004.stdout:ceph.monitoring (/srv/salt/ceph/monitoring):
2019-02-26T14:34:49.816 INFO:teuthology.orchestra.run.target192168000004.stdout:  target192168000004.teuthology:
2019-02-26T14:34:49.816 INFO:teuthology.orchestra.run.target192168000004.stdout:    grafana-server: Job for grafana-server.service failed because a timeout was exceeded.
2019-02-26T14:34:49.816 INFO:teuthology.orchestra.run.target192168000004.stdout:See "systemctl  status grafana-server.service" and "journalctl  -xe" for details.
2019-02-26T14:34:51.143 INFO:teuthology.orchestra.run.target192168000004.stderr:Exception in thread Thread-1:
2019-02-26T14:34:51.144 INFO:teuthology.orchestra.run.target192168000004.stderr:Traceback (most recent call last):
2019-02-26T14:34:51.145 INFO:teuthology.orchestra.run.target192168000004.stderr:  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
2019-02-26T14:34:51.145 INFO:teuthology.orchestra.run.target192168000004.stderr:    self.run()
2019-02-26T14:34:51.145 INFO:teuthology.orchestra.run.target192168000004.stderr:  File "/usr/lib/python3.6/site-packages/deepsea/monitor.py", line 585, in run
2019-02-26T14:34:51.145 INFO:teuthology.orchestra.run.target192168000004.stderr:    event.call()
2019-02-26T14:34:51.146 INFO:teuthology.orchestra.run.target192168000004.stderr:  File "/usr/lib/python3.6/site-packages/deepsea/monitor.py", line 469, in call
2019-02-26T14:34:51.146 INFO:teuthology.orchestra.run.target192168000004.stderr:    getattr(self.monitor, self.func)(self.event)
2019-02-26T14:34:51.146 INFO:teuthology.orchestra.run.target192168000004.stderr:  File "/usr/lib/python3.6/site-packages/deepsea/monitor.py", line 642, in end_stage
2019-02-26T14:34:51.146 INFO:teuthology.orchestra.run.target192168000004.stderr:    self._fire_event('stage_finished', tmp_stage)
2019-02-26T14:34:51.146 INFO:teuthology.orchestra.run.target192168000004.stderr:  File "/usr/lib/python3.6/site-packages/deepsea/monitor.py", line 601, in _fire_event
2019-02-26T14:34:51.147 INFO:teuthology.orchestra.run.target192168000004.stderr:    getattr(listener, event)(*args)
2019-02-26T14:34:51.147 INFO:teuthology.orchestra.run.target192168000004.stderr:  File "/usr/lib/python3.6/site-packages/deepsea/monitors/terminal_outputter.py", line 104, in stage_finished
2019-02-26T14:34:51.147 INFO:teuthology.orchestra.run.target192168000004.stderr:    PP.println("    {}: {}".format(substep['__id__'],
2019-02-26T14:34:51.147 INFO:teuthology.orchestra.run.target192168000004.stderr:KeyError: '__id__'
2019-02-26T14:34:51.148 INFO:teuthology.orchestra.run.target192168000004.stderr:
2019-02-26T14:34:51.283 ERROR:tasks.deepsea.orch:orchestration ceph.stage.2 failed. Here comes journalctl!
```

**Comment by smithfarm** [comment]
@rjfd See the previous comment - bug in the CLI?

**Comment by rjfd** [comment]
@smithfarm is this with salt 2019 already?

**Comment by smithfarm** [comment]
@rjfd Yup. There's a fixed salt-2019 in SES6.

```
2019-02-26T14:34:56.125 INFO:teuthology.orchestra.run.target192168000004.stdout:salt-2019.2.0~rc2-3.2.x86_64
2019-02-26T14:34:56.125 INFO:teuthology.orchestra.run.target192168000004.stdout:salt-api-2019.2.0~rc2-3.2.x86_64
2019-02-26T14:34:56.125 INFO:teuthology.orchestra.run.target192168000004.stdout:salt-master-2019.2.0~rc2-3.2.x86_64
2019-02-26T14:34:56.125 INFO:teuthology.orchestra.run.target192168000004.stdout:salt-minion-2019.2.0~rc2-3.2.x86_64
```

**Comment by smithfarm** [comment]
One way to merge this, then, would be to include a commit disabling the CLI version of the health-ok test in tier1.

@jschmid1 How does that sound to you?

**Comment by jschmid1** [comment]
> One way to merge this, then, would be to include a commit disabling the CLI version of the health-ok test in tier1.
> 
> @jschmid1 How does that sound to you?

If the fix is provided shortly after, sure :)

**Comment by jschmid1** [comment]
> If the fix is provided shortly after, sure :)

well ideally, we should provide the fix together with Jan's PR

**Comment by jan--f** [comment]
This look to me like the old monitoring deployment fails and the deepsea cli is not able to handle the error.
The reason for the failure is that the old style deployment tries to delete the rgw dashboard in case no rados gateways were deployed. It uses a deprecated http API andpoint for that. This reflects in the logs, search for `status=404` in the teuthology log.

Imho this can be safely ignored, as the error is expected and deepsea cli does not need to deal with this particular failure in the future.

**Pull request merged**
