### PR TITLE
pyhton-common: add kludge to rename deepsea's drive groups work with cephadm

### PR DESCRIPTION
**Pull request by sebastian-philipp**
"encryption" is now called "encrypted"

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

This is an alternative to https://github.com/ceph/ceph/pull/37230

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available @susebot commands</summary>

- `@susebot run make check`
- `@susebot run make check sles`
- `@susebot run make check leap`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
@sebastian-philipp Is this still something you eventually want to be merged?

**Comment by sebastian-philipp** [comment]
I'm not super keen on having this, but we got a bz that wanted to have thiis kludge. 

https://github.com/SUSE/ceph/pull/422/commits/7e7b213764c785d543c0b2a998eb1690116d1841

**Comment by smithfarm** [comment]
> we got a bz that wanted to have thiis kludge

Hm, which bz is that?

**Comment by smithfarm** [comment]
@sebastian-philipp Also, can you please rebase this on top of current `ses7` branch if you really want it.

**Comment by sebastian-philipp** [comment]
very well then. I'm ok with closing this.

**Pull request closed without merging**
