### PR TITLE
rgw ldap: enforce simple_bind w/LDAPv3

### PR DESCRIPTION
**Pull request by kmroz**
Found by Harald Klein <hklein@redhat.com>.

Signed-off-by: Matt Benjamin <mbenjamin@redhat.com>
(cherry picked from commit 08d54291435e4d1cb5e02cda3951bc6e8510b0e2)

This should fix the rpm lint warning preventing kraken from properly building in OBS.

### CODE REVIEW

**Comment by smithfarm** [comment]
lgtm, but re-assigning to @tserong

**Comment by smithfarm** [comment]
uh, https://github.com/ceph/ceph/pull/10593 has been merged upstream, so just rebase SUSE/ses5 to ceph/master, i.e.:

```
git remote add ceph http://github.com/ceph/ceph
git fetch ceph
git checkout ses5
git rebase ceph/master
git push -fu origin ses5
```

**Comment by tserong** [comment]
I'm happy to do the rebase -- @smithfarm, question: why are we rebasing on maser, not kraken?

**Comment by smithfarm** [comment]
@tserong Because #10593 was merged to master and ses5 is based on master. You can rebase on kraken, too, if you like - provided it contains the patch of course. 

At this phase of the kraken cycle, master and kraken are more-or-less the same. When luminous development starts, master and luminous will be the same thing.

It's a little confusing, but perhaps less so now that "next" is no longer being used. See http://docs.ceph.com/docs/master/dev/#what-is-merged-where-and-when for a detailed explanation.

**Comment by tserong** [comment]
@smithfarm, thanks. I'll run with master given ses5 is already based on that.

**Comment by smithfarm** [comment]
Upstream is currently manually merging master into kraken and vice versa on a regular basis. They're not really the same, of course, but close.

**Comment by tserong** [comment]
Merged, and builds (modulo errors unrelated to this PR)

**Pull request closed without merging**
