### PR TITLE
qa/suites/deepsea: drop unused subsuites

### PR DESCRIPTION
**Pull request by smithfarm**
These suites are not maintained, and they fail `teuthology-describe -s`

### CODE REVIEW

**Comment by kshtsk** [comment]
@smithfarm what about rest of the old tests? They fail too.

**Comment by kshtsk** [comment]
this suite is still failing: qa/suites/deepsea/wip

**Comment by kshtsk** [comment]
@smithfarm I hope that is final

**Comment by kshtsk** [comment]
```> for i in $(find qa/suites/deepsea -mindepth 1 -maxdepth 1 -print | grep -vF .qa) ; do echo "test $i" ; teuthology-describe -s $i ; done
test qa/suites/deepsea/tier1
# 4/4 /mnt/terra/suse/ceph/qa/suites/deepsea/tier1
test qa/suites/deepsea/tier4
# 58/58 /mnt/terra/suse/ceph/qa/suites/deepsea/tier4
test qa/suites/deepsea/dummy
# 2/2 /mnt/terra/suse/ceph/qa/suites/deepsea/dummy
test qa/suites/deepsea/tier2
# 26/26 /mnt/terra/suse/ceph/qa/suites/deepsea/tier2
test qa/suites/deepsea/test
# 6/6 /mnt/terra/suse/ceph/qa/suites/deepsea/test
test qa/suites/deepsea/build-validation
# 36/36 /mnt/terra/suse/ceph/qa/suites/deepsea/build-validation
test qa/suites/deepsea/tier0
# 2/2 /mnt/terra/suse/ceph/qa/suites/deepsea/tier0
test qa/suites/deepsea/wip
Traceback (most recent call last):
  File "/home/kyr/kshtsk/teuthology/v37/bin/teuthology-describe", line 11, in <module>
    load_entry_point('teuthology', 'console_scripts', 'teuthology-describe')()
  File "/home/kyr/kshtsk/teuthology/scripts/describe.py", line 78, in main
    teuthology.describe_tests.main(args)
  File "/home/kyr/kshtsk/teuthology/teuthology/describe_tests.py", line 20, in main
    describe_tests(args)
  File "/home/kyr/kshtsk/teuthology/teuthology/describe_tests.py", line 68, in describe_tests
    output_summary(suite_dir,
  File "/home/kyr/kshtsk/teuthology/teuthology/describe_tests.py", line 127, in output_summary
    mat, first, matlimit = _get_matrix(path, subset)
  File "/home/kyr/kshtsk/teuthology/teuthology/suite/build_matrix.py", line 75, in _get_matrix
    mat = _build_matrix(path)
  File "/home/kyr/kshtsk/teuthology/teuthology/suite/build_matrix.py", line 143, in _build_matrix
    submat = _build_matrix(
  File "/home/kyr/kshtsk/teuthology/teuthology/suite/build_matrix.py", line 127, in _build_matrix
    submat = _build_matrix(
  File "/home/kyr/kshtsk/teuthology/teuthology/suite/build_matrix.py", line 143, in _build_matrix
    submat = _build_matrix(
  File "/home/kyr/kshtsk/teuthology/teuthology/suite/build_matrix.py", line 84, in _build_matrix
    raise IOError('%s does not exist (abs %s)' % (path, os.path.abspath(path)))
OSError: /mnt/terra/suse/ceph/qa/suites/deepsea/wip/all-osd-configs/clusters/1node4disks.yaml does not exist (abs /mnt/terra/suse/ceph/qa/suites/deepsea/wip/all-osd-configs/clusters/1node4disks.yaml)
test qa/suites/deepsea/functional-1node
# 2/2 /mnt/terra/suse/ceph/qa/suites/deepsea/functional-1node
test qa/suites/deepsea/functional-3nodes
# 2/2 /mnt/terra/suse/ceph/qa/suites/deepsea/functional-3nodes
test qa/suites/deepsea/tier3
# 6/6 /mnt/terra/suse/ceph/qa/suites/deepsea/tier3
test qa/suites/deepsea/salt
# 10/10 /mnt/terra/suse/ceph/qa/suites/deepsea/salt
```

**Comment by smithfarm** [comment]
@kshtsk Actually, I think it just bails out at the first dangling symlink it encounters. I have to fix all of them under `wip`.

**Comment by smithfarm** [comment]
@kshtsk Please try again.

**Comment by kshtsk** [comment]
@smithfarm yes, you're right, all of the `deepsea/wip/*` are a bit lame:
```
for i in $(find qa/suites/deepsea/wip -mindepth 1 -maxdepth 1 -print | grep -vF .qa) ; do echo "test $i" ; teuthology-describe -s $i ; done
test qa/suites/deepsea/wip/pynfs
# 1/1 /mnt/terra/suse/ceph/qa/suites/deepsea/wip/pynfs
test qa/suites/deepsea/wip/migration
Traceback (most recent call last):
  File "/home/kyr/kshtsk/teuthology/v37/bin/teuthology-describe", line 11, in <module>
    load_entry_point('teuthology', 'console_scripts', 'teuthology-describe')()
  File "/home/kyr/kshtsk/teuthology/scripts/describe.py", line 78, in main
    teuthology.describe_tests.main(args)
  File "/home/kyr/kshtsk/teuthology/teuthology/describe_tests.py", line 20, in main
    describe_tests(args)
  File "/home/kyr/kshtsk/teuthology/teuthology/describe_tests.py", line 68, in describe_tests
    output_summary(suite_dir,
  File "/home/kyr/kshtsk/teuthology/teuthology/describe_tests.py", line 127, in output_summary
    mat, first, matlimit = _get_matrix(path, subset)
  File "/home/kyr/kshtsk/teuthology/teuthology/suite/build_matrix.py", line 75, in _get_matrix
    mat = _build_matrix(path)
  File "/home/kyr/kshtsk/teuthology/teuthology/suite/build_matrix.py", line 127, in _build_matrix
    submat = _build_matrix(
  File "/home/kyr/kshtsk/teuthology/teuthology/suite/build_matrix.py", line 84, in _build_matrix
    raise IOError('%s does not exist (abs %s)' % (path, os.path.abspath(path)))
OSError: /mnt/terra/suse/ceph/qa/suites/deepsea/wip/migration/ceph_cm_salt.yaml does not exist (abs /mnt/terra/suse/ceph/qa/suites/deepsea/wip/migration/ceph_cm_salt.yaml)
test qa/suites/deepsea/wip/all-osd-configs
# 84/84 /mnt/terra/suse/ceph/qa/suites/deepsea/wip/all-osd-configs
test qa/suites/deepsea/wip/big
Traceback (most recent call last):
  File "/home/kyr/kshtsk/teuthology/v37/bin/teuthology-describe", line 11, in <module>
    load_entry_point('teuthology', 'console_scripts', 'teuthology-describe')()
  File "/home/kyr/kshtsk/teuthology/scripts/describe.py", line 78, in main
    teuthology.describe_tests.main(args)
  File "/home/kyr/kshtsk/teuthology/teuthology/describe_tests.py", line 20, in main
    describe_tests(args)
  File "/home/kyr/kshtsk/teuthology/teuthology/describe_tests.py", line 68, in describe_tests
    output_summary(suite_dir,
  File "/home/kyr/kshtsk/teuthology/teuthology/describe_tests.py", line 127, in output_summary
    mat, first, matlimit = _get_matrix(path, subset)
  File "/home/kyr/kshtsk/teuthology/teuthology/suite/build_matrix.py", line 75, in _get_matrix
    mat = _build_matrix(path)
  File "/home/kyr/kshtsk/teuthology/teuthology/suite/build_matrix.py", line 127, in _build_matrix
    submat = _build_matrix(
  File "/home/kyr/kshtsk/teuthology/teuthology/suite/build_matrix.py", line 84, in _build_matrix
    raise IOError('%s does not exist (abs %s)' % (path, os.path.abspath(path)))
OSError: /mnt/terra/suse/ceph/qa/suites/deepsea/wip/big/ceph_cm_salt.yaml does not exist (abs /mnt/terra/suse/ceph/qa/suites/deepsea/wip/big/ceph_cm_salt.yaml)
```

**Pull request merged**
