### PR TITLE
spec: cephadm requires podman

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Fixes: bsc#1174529

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available @susebot commands</summary>

- `@susebot run make check`
- `@susebot run make check sles`
- `@susebot run make check leap`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
@tserong @Martin-Weiss @jan--f @ricardoasmarques Please see my comment, above. Any thoughts?

**Comment by smithfarm** [comment]
I avoid downstream spec-file commits like the plague. I opened 

https://github.com/ceph/ceph/pull/36995

to replace this.

**Comment by Martin-Weiss** [comment]
> 
> 
> @tserong @Martin-Weiss @jan--f @ricardoasmarques Please see my comment, above. Any thoughts?

It reads a bit like we need a new RPM feature where we can distinguish between "installed in image" vs. "installed in native installation".

Why do we need ceph-mgr-cephadm / cephadm / podman within the container? IMO the design flaw might be that we have "just one image that rules them all".. if we would have micro-service focused images - we might not require the management stack to be included in each image..

**Comment by smithfarm** [comment]
@sebastian-philipp How about having the `cephadm` RPM require podman (instead of `ceph-mgr-cephadm`)? It seems that all cluster nodes have the `cephadm` package installed, and it could bring in podman as a dependency.

**Comment by sebastian-philipp** [comment]
> @sebastian-philipp How about having the `cephadm` RPM require podman (instead of `ceph-mgr-cephadm`)?

Actually this is the case! But indeed, `ceph-mgr-cephadm` depends on  `cephadm`.

It seems that all cluster nodes have the `cephadm` package installed, and it could bring in podman as a dependency. Yes. `cephadm` now depends on `podman`.

> 
> Alternatively, the `cephadm adopt` command could detect that a node is running SUSE and install podman?

nah. we should do that via the `cephadm` dependencies

**Comment by smithfarm** [comment]
https://github.com/ceph/ceph/pull/36995 has been merged into master upstream and I cherry-picked it into ses7 downstream in anticipation of it getting backported to the upstream `octopus` branch.

> cephadm now depends on podman

Right, and I assume that means the Ceph Base container image now contains both `cephadm` and `podman` :-/

**Comment by sebastian-philipp** [comment]
> Ceph Base container image now contains both `cephadm` and `podman` :-/

The ceph base image indeed needs `cephadm`, but not `podman`. As it needs to access the the cephadm code.

**Comment by smithfarm** [comment]
> The ceph base image indeed needs `cephadm`, but not `podman`. As it needs to access the the cephadm code.

If `cephadm` depends on `podman`, how can `podman` be excluded from the ceph base image, though?

**Comment by sebastian-philipp** [comment]
https://github.com/ceph/ceph/blob/839c8ec6ba2998ee4382c8a9477f6f1b8ee8c905/src/pybind/mgr/cephadm/module.py#L312-L318

**Pull request closed without merging**
