### PR TITLE
Merge upstream v12.2.2

### PR DESCRIPTION
**Pull request by smithfarm**
Merge tag 'v12.2.2' into wip-12-2-2
    
v12.2.2
    
Conflicts:
            debian/ceph-osd.install
            src/90-ceph-osd.conf

### CODE REVIEW

**Comment by smithfarm** [comment]
@ddiss Could you take a quick look? The merge went fine except for conflicts in 

```
debian/ceph-osd.install
src/90-ceph-osd.conf
```

AFAICT these conflicts are caused by https://github.com/SUSE/ceph/pull/157 so we need to be careful not to break that fix. Thanks!

**Comment by smithfarm** [comment]
```
[ 47%] Building CXX object src/osd/CMakeFiles/osd.dir/PrimaryLogPG.cc.o
Scanning dependencies of target ec_shec_sse4
[ 47%] Linking CXX shared library ../../../lib/libec_shec_sse4.so
Scanning dependencies of target gtest_main
[ 47%] Building CXX object src/googletest/googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 47%] Built target ec_shec_sse4
[ 47%] Building CXX object src/osd/CMakeFiles/osd.dir/ReplicatedBackend.cc.o
[ 47%] Linking CXX static library ../../../../lib/libgtest_main.a
[ 47%] Built target gtest_main
[ 47%] Building CXX object src/osd/CMakeFiles/osd.dir/ECBackend.cc.o
[ 47%] Building CXX object src/osd/CMakeFiles/osd.dir/ECTransaction.cc.o
[ 47%] Building CXX object src/osd/CMakeFiles/osd.dir/PGBackend.cc.o
[ 47%] Building CXX object src/librbd/CMakeFiles/rbd_internal.dir/object_map/UpdateRequest.cc.o
[ 47%] Building CXX object src/librbd/CMakeFiles/rbd_internal.dir/operation/DisableFeaturesRequest.cc.o
[ 47%] Building CXX object src/librbd/CMakeFiles/rbd_internal.dir/operation/EnableFeaturesRequest.cc.o
[ 48%] Building CXX object src/librbd/CMakeFiles/rbd_internal.dir/operation/FlattenRequest.cc.o
[ 48%] Building CXX object src/librbd/CMakeFiles/rbd_internal.dir/operation/MetadataRemoveRequest.cc.o
[ 48%] Linking CXX static library ../../lib/libmon.a
[ 48%] Built target mon
[ 48%] Building CXX object src/librbd/CMakeFiles/rbd_internal.dir/operation/MetadataSetRequest.cc.o
Scanning dependencies of target unittest_backport14
[ 48%] Building CXX object src/test/common/CMakeFiles/unittest_backport14.dir/test_backport14.cc.o
[ 48%] Building CXX object src/osd/CMakeFiles/osd.dir/OSDCap.cc.o
[ 48%] Linking CXX executable ../../../bin/unittest_backport14
[ 48%] Built target unittest_backport14
[ 48%] Building CXX object src/osd/CMakeFiles/osd.dir/Session.cc.o
[ 48%] Building CXX object src/osd/CMakeFiles/osd.dir/SnapMapper.cc.o
[ 48%] Building CXX object src/osd/CMakeFiles/osd.dir/ScrubStore.cc.o
/tmp/release/sles/WORKDIR/BUILD/ceph-12.2.2-354-g7481b9fac4/src/osd/PrimaryLogPG.cc: In member function 'int PrimaryLogPG::do_extent_cmp(PrimaryLogPG::OpContext*, OSDOp&, bool)':
/tmp/release/sles/WORKDIR/BUILD/ceph-12.2.2-354-g7481b9fac4/src/osd/PrimaryLogPG.cc:4735:50: error: no matching function for call to 'PrimaryLogPG::finish_extent_cmp(OSDOp&, ceph::bufferlist)'
     return finish_extent_cmp(osd_op, bufferlist{});
                                                  ^
/tmp/release/sles/WORKDIR/BUILD/ceph-12.2.2-354-g7481b9fac4/src/osd/PrimaryLogPG.cc:4735:50: note: candidate is:
In file included from /tmp/release/sles/WORKDIR/BUILD/ceph-12.2.2-354-g7481b9fac4/src/osd/PrimaryLogPG.cc:21:0:
/tmp/release/sles/WORKDIR/BUILD/ceph-12.2.2-354-g7481b9fac4/src/osd/PrimaryLogPG.h:1336:7: note: int PrimaryLogPG::finish_extent_cmp(OSDOp&, const bufferlist&, bool)
   int finish_extent_cmp(OSDOp& osd_op, const bufferlist &read_bl, bool munged);
       ^
/tmp/release/sles/WORKDIR/BUILD/ceph-12.2.2-354-g7481b9fac4/src/osd/PrimaryLogPG.h:1336:7: note:   candidate expects 3 arguments, 2 provided
[ 48%] Building CXX object src/librbd/CMakeFiles/rbd_internal.dir/operation/ObjectMapIterate.cc.o
```

**Comment by ddiss** [comment]
Looks like fallout from the SES cmpext OP munging. I'll take a look at this.

**Comment by smithfarm** [comment]
@ddiss Right. I was just going to say https://github.com/SUSE/ceph/commit/a8ae498fc19

**Comment by ddiss** [comment]
I have a one liner to address this - the build failure is fallout from the fix for http://tracker.ceph.com/issues/21629 , which conflicts with a8ae498 cmpext munging.

**Comment by smithfarm** [comment]
@ddiss ACK. If you push the oneliner to github I'll cherry-pick it into this PR?

**Comment by ddiss** [comment]
@smithfarm pushed to https://github.com/ddiss/ceph/commit/90d85b345bf4697f91aa106849a468e9de6aa881 . Sorry about the wait, just wanted to run the full build and cmpext unit tests before pushing

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
bleah, accidentally used `-x` on the cherry-pick. Will amend the commit after make check completes.

**Comment by smithfarm** [comment]
health-ok and health-igw tests pass, but Stage 3 fails if rgw or mds role is added. Needs investigation:

http://213.32.78.239:8081/ubuntu-2017-12-12_23:21:41-deepsea:basic-wip-12-2-2---basic-openstack/

**Comment by smithfarm** [comment]
I gleaned the following from the deepsea log: `'salt_|-check if mon processes are still running on target137074025153.teuthology after restarting mons_|-check if mon processes are still running on target137074025153.teuthology after restarting mons_|-state': {'comment': 'Run failed on minions: target137074025153.teuthology\nFailures:\n    target137074025153.teuthology:\n    ----------\n              ID: wait processes\n        Function: module.run\n            Name: cephprocesses.wait\n          Result: False\n         Comment: Module function cephprocesses.wait executed\n         Started: 23:34:53.080566\n        Duration: 136867.361 ms\n         Changes:   \n                  ----------\n                  ret:\n                      False\n    \n    Summary for target137074025153.teuthology\n    ------------\n    Succeeded: 0 (changed=1)\n    Failed:    1\n    ------------\n    Total states run:     1\n    Total run time: 136.867 s\n', 'name': 'check if mon processes are still running on target137074025153.teuthology after restarting mons', 'start_time': '23:34:52.707820', 'result': False, 'duration': 137300.998, '__run_num__': 18, '__jid__': '20171212233452742212', 'changes': {}, '__id__': 'check if mon processes are still running on target137074025153.teuthology after restarting mons'}`

**Comment by smithfarm** [comment]
I don't think the failures are related to this PR. I ran a baseline test against `ses5` branch and Stage 3 fails in the same way.

**Comment by smithfarm** [comment]
Re-ran the integration suite using a slightly older version of DeepSea - results are much improved: http://213.32.78.239:8081/ubuntu-2017-12-13_11:24:06-deepsea:basic-wip-12-2-2---basic-openstack/

(The openattic failure is "too many PGs" - a known issue with the tests. The nfs-ganesha failure is unrelated to this PR.)

**Pull request merged**
