### PR TITLE
qa/deepsea: run clock.check once instead of clock twice

### PR DESCRIPTION
**Pull request by smithfarm**
After switching the CI from legacy downstream teuthology to upstream
teuthology, we need to explicitly set "clock_sync_task: true" in the test
definition in order to trigger the following code in teuthology/run.py:

    # clock_sync_task: 'clock' or 'clock.check'
    clock_sync_task = config.get('clock_sync_task', 'clock')
    init_tasks.append({clock_sync_task: None})

Also, since the clocks are synced via user-data, drop "clock" from the task
list.

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
NOTE: THIS WILL NEED TO BE CHERRY-PICKED TO SES5 AS WELL

**Comment by kshtsk** [comment]
requires testing

**Comment by smithfarm** [comment]
@kshtsk I'm not sure if this is a good idea, after all. Keep in mind, I tested it in teuthology **legacy** only!

Here's what happens before the patch in this PR is applied:

```
2019-09-25T12:39:32.181 INFO:teuthology.run_tasks:Running task clock.check...
2019-09-25T12:39:32.189 INFO:teuthology.task.clock:Checking initial clock skew...
2019-09-25T12:39:32.189 INFO:teuthology.orchestra.run.target192168000034:Running: 'PATH=/usr/bin:/usr/sbin ntpq -p || PATH=/usr/bin:/usr/sbin chronyc sources || true'
2019-09-25T12:39:32.232 INFO:teuthology.orchestra.run.target192168000034.stderr:bash: ntpq: command not found
2019-09-25T12:39:32.626 INFO:teuthology.orchestra.run.target192168000034.stdout:210 Number of sources = 4
2019-09-25T12:39:32.626 INFO:teuthology.orchestra.run.target192168000034.stdout:MS Name/IP address         Stratum Poll Reach LastRx Last sample
2019-09-25T12:39:32.627 INFO:teuthology.orchestra.run.target192168000034.stdout:===============================================================================
2019-09-25T12:39:32.627 INFO:teuthology.orchestra.run.target192168000034.stdout:^+ lithium.constant.com          2   6    37    30   +305us[ +450us] +/-   86ms
2019-09-25T12:39:32.627 INFO:teuthology.orchestra.run.target192168000034.stdout:^- linode227395.stevemeacha>     2   6    37    29  +2496us[+2496us] +/-   81ms
2019-09-25T12:39:32.627 INFO:teuthology.orchestra.run.target192168000034.stdout:^+ time.richiemcintosh.com       2   6    37    29   -251us[ -106us] +/-   97ms
2019-09-25T12:39:32.627 INFO:teuthology.orchestra.run.target192168000034.stdout:^* 216.126.233.109               2   6    37    29    -40us[ +105us] +/-   61ms
2019-09-25T12:39:32.628 INFO:teuthology.run_tasks:Running task clock...
2019-09-25T12:39:32.640 INFO:teuthology.task.clock:Syncing clocks and checking initial clock skew...
2019-09-25T12:39:32.640 INFO:teuthology.orchestra.run.target192168000034:Running: 'sudo systemctl stop ntpd.service || sudo systemctl stop chronyd.service ; sudo ntpd -gq || sudo chronyc makestep ; sudo systemctl start ntpd.service || sudo systemctl start chronyd.service ; PATH=/usr/bin:/usr/sbin ntpq -p || PATH=/usr/bin:/usr/sbin chronyc sources || true'
2019-09-25T12:39:32.772 INFO:teuthology.orchestra.run.target192168000034.stderr:Failed to stop ntpd.service: Unit ntpd.service not loaded.
2019-09-25T12:39:32.883 INFO:teuthology.orchestra.run.target192168000034.stderr:sudo: ntpd: command not found
2019-09-25T12:39:32.945 INFO:teuthology.orchestra.run.target192168000034.stdout:506 Cannot talk to daemon
2019-09-25T12:39:33.003 INFO:teuthology.orchestra.run.target192168000034.stderr:Failed to start ntpd.service: Unit ntpd.service not found.
2019-09-25T12:39:33.083 INFO:teuthology.orchestra.run.target192168000034.stderr:bash: ntpq: command not found
2019-09-25T12:39:33.471 INFO:teuthology.orchestra.run.target192168000034.stdout:210 Number of sources = 4
2019-09-25T12:39:33.472 INFO:teuthology.orchestra.run.target192168000034.stdout:MS Name/IP address         Stratum Poll Reach LastRx Last sample
2019-09-25T12:39:33.473 INFO:teuthology.orchestra.run.target192168000034.stdout:===============================================================================
2019-09-25T12:39:33.473 INFO:teuthology.orchestra.run.target192168000034.stdout:^? mirror1.sjc02.svwh.net        0   6     0     -     +0ns[   +0ns] +/-    0ns
2019-09-25T12:39:33.473 INFO:teuthology.orchestra.run.target192168000034.stdout:^? t1.time.bf1.yahoo.com         0   6     0     -     +0ns[   +0ns] +/-    0ns
2019-09-25T12:39:33.473 INFO:teuthology.orchestra.run.target192168000034.stdout:^? y.ns.gin.ntt.net              0   6     0     -     +0ns[   +0ns] +/-    0ns
2019-09-25T12:39:33.474 INFO:teuthology.orchestra.run.target192168000034.stdout:^? shed.galexander.org           0   6     0     -     +0ns[   +0ns] +/-    0ns
```

In other words, `clock` task is not run twice. Maybe there is a difference between upstream and legacy teuthology in this respect? By running `clock` at the beginning, the time skews are reduced to `0ns` which is a good thing.

With this patch applied, we get:

```
  suite_branch: wip-fix-double-clock
...
2019-09-25T12:44:44.317 INFO:teuthology.run_tasks:Running task clock.check...
2019-09-25T12:44:44.328 INFO:teuthology.task.clock:Checking initial clock skew...
2019-09-25T12:44:44.328 INFO:teuthology.orchestra.run.target192168000059:Running: 'PATH=/usr/bin:/usr/sbin ntpq -p || PATH=/usr/bin:/usr/sbin chronyc sources || true'
2019-09-25T12:44:44.438 INFO:teuthology.orchestra.run.target192168000059.stderr:bash: ntpq: command not found
2019-09-25T12:44:44.709 INFO:teuthology.orchestra.run.target192168000059.stdout:210 Number of sources = 4
2019-09-25T12:44:44.709 INFO:teuthology.orchestra.run.target192168000059.stdout:MS Name/IP address         Stratum Poll Reach LastRx Last sample
2019-09-25T12:44:44.709 INFO:teuthology.orchestra.run.target192168000059.stdout:===============================================================================
2019-09-25T12:44:44.709 INFO:teuthology.orchestra.run.target192168000059.stdout:^- hydrogen.constant.com         2   6    37    30  -3170us[-3170us] +/-   84ms
2019-09-25T12:44:44.710 INFO:teuthology.orchestra.run.target192168000059.stdout:^+ clock.team-cymru.org          2   6    37    31  -4338us[-5424us] +/-   68ms
2019-09-25T12:44:44.710 INFO:teuthology.orchestra.run.target192168000059.stdout:^+ y.ns.gin.ntt.net              2   6    37    31    +90us[ -995us] +/-   79ms
2019-09-25T12:44:44.710 INFO:teuthology.orchestra.run.target192168000059.stdout:^* ntp.xtom.com                  2   6    37    30  +2090us[+1005us] +/-   33ms
```

And since the `clock` task is not run, the skew remains, though in this one case it did not cause the test to fail.

**Comment by kshtsk** [comment]
@smithfarm which suite have you been running against?

**Comment by smithfarm** [comment]
deepsea:tier1:health-ok 

see http://10.86.0.8:8081/

**Comment by kshtsk** [comment]
http://teuth-ses.prv.suse.net:8081/runner-2019-09-26_20:18:12-deepsea:tier1:health-ok-ses6-downstream-commits-none-basic-ecp/

**Comment by kshtsk** [comment]
Well it has the same behavior as your latter printout:
```
2019-09-26T20:21:33.312 INFO:teuthology.run_tasks:Running task clock.check...
2019-09-26T20:21:33.328 INFO:teuthology.task.clock:Checking initial clock skew...
2019-09-26T20:21:33.328 INFO:teuthology.orchestra.run.target-ses-081:Running:
2019-09-26T20:21:33.328 INFO:teuthology.orchestra.run.target-ses-081:> PATH=/usr/bin:/usr/sbin ntpq -p || PATH=/usr/bin:/usr/sbin chronyc sources || true
2019-09-26T20:21:33.390 INFO:teuthology.orchestra.run.target-ses-081.stderr:bash: ntpq: command not found
2019-09-26T20:21:34.047 INFO:teuthology.orchestra.run.target-ses-081.stdout:210 Number of sources = 4
2019-09-26T20:21:34.047 INFO:teuthology.orchestra.run.target-ses-081.stdout:MS Name/IP address         Stratum Poll Reach LastRx Last sample
2019-09-26T20:21:34.048 INFO:teuthology.orchestra.run.target-ses-081.stdout:===============================================================================
2019-09-26T20:21:34.048 INFO:teuthology.orchestra.run.target-ses-081.stdout:^+ io.crash-override.org         2   6    17     8   +278us[ -648us] +/-   67ms
2019-09-26T20:21:34.048 INFO:teuthology.orchestra.run.target-ses-081.stdout:^+ nu.binary.net                 2   6    17     7  +5222us[+5222us] +/-   71ms
2019-09-26T20:21:34.048 INFO:teuthology.orchestra.run.target-ses-081.stdout:^+ unifi.versadns.com            2   6    17     8    +34us[ -892us] +/-  120ms
2019-09-26T20:21:34.049 INFO:teuthology.orchestra.run.target-ses-081.stdout:^* ntp1.wiktel.com               1   6    17     8  -3573us[-4499us] +/-   46ms
```

**Comment by kshtsk** [comment]
The user-data for those nodes is:
```2019-09-26T20:19:14.258 DEBUG:teuthology.provision.cloud.openstack:Using userdata: #cloud-config
hostname: target-ses-037.ecp.suse.de
manage_etc_hosts: true
runcmd:
- 'cat > /etc/resolv.conf << EOF

  search ecp.suse.de

  nameserver 192.168.0.17

  EOF

  '
- zypper in -y git wget rsyslog || true
- zypper in -y lsb-release make gcc gcc-c++ chrony || true
- systemctl enable chronyd.service || true
- systemctl start chronyd.service || true
- - passwd
  - -d
  - ubuntu
- - touch
  - /.teuth_provisioned
```

**Comment by kshtsk** [comment]
So I didn't get why do we need:
```clock_sync_task: clock.check```
Since it does nothing, it is better to leave the default value 'clock' so it can sync the values.

**Comment by kshtsk** [comment]
I mean the fix would be "run clock once instead of twice"

**Comment by smithfarm** [comment]
@kshtsk Do you remember why we introduced `clock_sync_task` in https://github.com/ceph/teuthology/commit/1d5452782 ? I thought we intended to use it.

Be that as it may, I will follow your suggestion and just run `clock` once.

**Comment by smithfarm** [comment]
Please also see https://github.com/SUSE/teuthology/pull/205

**Comment by kshtsk** [comment]
> @kshtsk Do you remember why we introduced `clock_sync_task` in [ceph/teuthology@1d54527](https://github.com/ceph/teuthology/commit/1d5452782) ? I thought we intended to use it.
> 
> Be that as it may, I will follow your suggestion and just run `clock` once.

As far as I remember you wanted to have a flexible way to set clock sync task, I didn't realized you're adding clock task in deepsea suites exclusively. And also, maybe before this there was a code in user-data for sle and opensuse for openstack backend which runs the same that clock task does.

**Comment by smithfarm** [comment]
@kshtsk Please tell me what you want me to do here. I'm happy to just close it.

**Comment by kshtsk** [comment]
Hm, shouldn't this PR be closed already?

**Pull request closed without merging**
