### PR TITLE
ceph-volume lvmcache plugin

### PR DESCRIPTION
**Pull request by mogeb**
Do not merge before #27791 is part of SES6.
Fixes: https://jira.suse.de/browse/SES-267

### CODE REVIEW

**Comment by smithfarm** [comment]
@mogeb Please rebase?

Also, I can confirm that SES6 now has the prerequisite commits mentioned in the PR description:

```
smithfarm@linux-8ne7:~/src/ceph/SUSE/ceph> git branch --contains f5edf3b | grep ses6-m15
* ses6-m15
```

So this PR can go forward?

**Comment by smithfarm** [comment]
@mogeb Is there any way the number of commits be reduced?

**Comment by mogeb** [comment]
@smithfarm of course, I will rebase and reduce the number of commits.

**Comment by mogeb** [comment]
@smithfarm done - there are also some tests as part of this commit, can we make sure that they are ran as part of ceph-volume's tests?

**Comment by smithfarm** [comment]
Merged manually by cherry-picking f88ec24

**Pull request closed without merging**
